services:
  postgres:
    image: 'postgres:alpine3.19'
    container_name: 'pet-shop'
    environment:
      - 'POSTGRES_DB=pet_shop'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'