spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pet_shop
    username: admin
    password: root

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  management:
    server:
      port:8080